# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0002_payvariant_payvar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount_from', models.BigIntegerField(default=0)),
                ('amount_to', models.BigIntegerField(default=0)),
                ('period_from', models.SmallIntegerField()),
                ('period_to', models.SmallIntegerField()),
                ('is_pensioner', models.BooleanField(default=False)),
            ],
        ),
    ]
