# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0004_loanprogram_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprogram',
            name='rate',
            field=models.FloatField(),
        ),
    ]
