# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0005_auto_20160228_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanprogram',
            options={'verbose_name': ''},
        ),
    ]
