# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0008_auto_20160309_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='payvariant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
