# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0009_payvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payvariant',
            name='payvar_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
