from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    client = models.OneToOneField(User, null=True)
    surname = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    patronymic = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255)
    homephone = models.CharField(max_length=255)
    birth = models.DateField(max_length=255)
    address_reg_index = models.CharField(max_length=255)
    address_reg_region = models.CharField(max_length=255)
    address_reg_district = models.CharField(max_length=255, null=True, blank=True)
    address_reg_city = models.CharField(max_length=255)
    address_reg_street = models.CharField(max_length=255)
    address_reg_house = models.CharField(max_length=255)
    address_reg_building = models.CharField(max_length=255, null=True, blank=True)
    address_reg_apartment = models.CharField(max_length=255, null=True, blank=True)
    address_fact_index = models.CharField(max_length=255)
    address_fact_region = models.CharField(max_length=255)
    address_fact_district = models.CharField(max_length=255, null=True, blank=True)
    address_fact_city = models.CharField(max_length=255)
    address_fact_street = models.CharField(max_length=255)
    address_fact_house = models.CharField(max_length=255)
    address_fact_building = models.CharField(max_length=255, null=True, blank=True)
    address_fact_apartment = models.CharField(max_length=255, null=True, blank=True)
    passport_serie = models.CharField(max_length=255)
    passport_number = models.CharField(max_length=255)
    kod = models.CharField(max_length=255)
    passport_date = models.CharField(max_length=255)
    passport_father = models.CharField(max_length=255)
    gender = models.CharField(max_length=255)
    birthplace = models.CharField(max_length=255)
    dohod = models.CharField(max_length=255)
    izhd = models.CharField(max_length=255)
    inn = models.CharField(max_length=255, null=True, blank=True)
    bank_ls = models.CharField(max_length=20, null=True, blank=True)
    bank_bik = models.CharField(max_length=9, null=True, blank=True)


    def unicode(self):
        return '{} {} {}'.format(self.surname, self.name, self.patronymic)
