# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmfo', '0003_auto_20160227_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
