# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmfo', '0004_auto_20160228_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bank_ls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
