# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanhistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_ls',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanSumm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payVar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='product',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='summ',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
